service: hubworld-gateway
app: hubworld
org: lmuller18

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  package:
    individually: true
    exclude:
      - node_modules

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'

functions:
  gateway:
    handler: src/handler.handler
    environment:
      ACCOUNTS_FEDERATION_URL: ${file(./serverless.env.yml):${self:provider.stage}.ACCOUNTS_FEDERATION_URL}
      POSTS_FEDERATION_URL: ${file(./serverless.env.yml):${self:provider.stage}.POSTS_FEDERATION_URL}
    events:
      - http:
          path: api
          method: post
          cors: true
