service: hubworld
app: hubworld
org: lmuller18

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  package:
    individually: true
    exclude:
      - node_modules
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/Hub*'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'

functions:
  gateway:
    handler: src/handler.handler
    events:
      - http:
          path: api
          method: post
          cors: true
