service: hubworld
app: hubworld
org: lmuller18

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  package:
    individually: true
    exclude:
      - node_modules
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/Hub*'
    - Effect: Allow
      Action:
        - lambda:GetLayerVersion
      Resource: '*'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'

functions:
  graphql:
    handler: src/handler.handler
    layers:
      - { Ref: DependenciesLayerLambdaLayer }
    events:
      - http:
          path: api
          method: post
          cors: true

layers:
  dependenciesLayer:
    path: src/layer
    package:
      include:
        - node_modules
        - node_modules/**/
    compatibleRuntimes:
      - nodejs10.x
